<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Returns the N last active products
     *
     * @param null $limit
     */
    public function getLastActiveProducts($limit = null)
    {
        return $this->findBy(
            ['status' => true],
            ['id' => 'DESC'],
            $limit
        );
    }
}
